name: Atualizar Conta Azul_contas-a-receber_27

on:
  schedule:
    - cron: '30 6 * * *'  # todos os dias às 04:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python contas-a-receber_27.py
